services:
  - type: web
    name: mars-explorer-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NASA_API_KEY
        value: bK5ADcBXRPaROH3lKVCedfJLUasrKNZYlTx4fH4p
      - key: NASA_API_BASE_URL
        value: https://api.nasa.gov
      - key: MONGODB_URI
        value: mongodb://localhost:27017/nasa-space-explorer
      - key: CORS_ORIGIN
        value: "*"
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CACHE_TTL
        value: 3600
    autoDeploy: true
    branch: main
    rootDir: backend
